Insert Contact Added with Email Send.
alkemyTech/OT232-server pull request #69
Opened 2022-07-04 20:51 UTC by lmosquera93

Insert Contact added with Email Sended.

Picture Attached.
![CaptureInsertContactEmail](https://user-images.githubusercontent.com/71273476/177215320-6dcb4042-f230-40b4-b469-6018e2ccb2e9.JPG)

2022-07-04 21:53 UTC, emmanuelranone requested changes
El código lo veo bien. Adjuntame una captura de la recepción del mail.

2022-07-05 01:47 UTC, lmosquera93 commented
Email Send confirmation

![imagen](https://user-images.githubusercontent.com/71273476/177233578-73631a7f-bfda-4b9a-b0a9-c83cf7479f27.png)

2022-07-05 12:47 UTC, emmanuelranone requested changes
Fijate que me estás enviando la captura de la creación de usuario y vos estás dejando un contacto.
O te equivocaste de captura al enviar o estás enviando mal el mail.

2022-07-05 14:58 UTC, lmosquera93 commented
![CaptureEmailContact](https://user-images.githubusercontent.com/71273476/177357807-e2866302-86fa-4dc0-af8a-f891b061d75a.JPG)

2022-07-05 15:09 UTC, emmanuelranone approved these changes

2022-07-05 15:09 UTC, merged