View Slides attached to Organization.
alkemyTech/OT232-server pull request #91
Opened 2022-07-09 10:10 UTC by lmosquera93

View Slides attached to Organization.
Add Seed Slides.
Modification Organization Seed.

Attached Images:
![SlideOrganization](https://user-images.githubusercontent.com/71273476/178101288-ed176b71-2828-4982-8c1d-f502b5704457.JPG)

2022-07-10 18:39 UTC, emmanuelranone requested changes
En el pr se ve una lista de slides, pero la organización está en null. Se deberían ver los datos de la organización y además los slides que tiene la misma.

2022-07-10 19:23 UTC, lmosquera93 commented
Fixed problem, show organization. 

Image Attached:
![CaptureFixedSlidesOrganization](https://user-images.githubusercontent.com/71273476/178159097-935138ba-db34-41fe-98bb-baeb39931c4d.JPG)

2022-07-10 23:12 UTC, emmanuelranone requested changes
Ahora quedó mejor, pero estas mostrando los campos de isDeleted y el timestamp que habíamos quedado en no mostrarlos.

2022-07-11 20:30 UTC, lmosquera93 commented
Fixed Slides Organization.

Capture Attached:
![CaptureSlidesOrganizationFixed](https://user-images.githubusercontent.com/71273476/178352693-903b2021-d345-454f-9c88-e12550880313.JPG)

2022-07-11 22:19 UTC, emmanuelranone approved these changes

2022-07-11 22:19 UTC, merged